#!/usr/bin/env bash
echo "== create bucket"
# Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1

aws s3api create-bucket \
--bucket $BUCKET_NAME \
--region ca-central-1 \
--create-bucket-configuration \
LocationConstraint=ca-central-1