#!/usr/bin/env bash
echo "== delete objects"

# Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1



#Get the objects type and save to a file
aws s3api list-objects-v2 \
  --bucket $BUCKET_NAME \
  --query 'Contents[].Key' \
  | jq '{Objects: [.[] | {Key: .}]}' > /tmp/delete_objects.json

#do delete based on the file
aws s3api delete-objects --bucket $BUCKET_NAME --delete file:///tmp/delete_objects.json
