#!/usr/bin/env bash
echo "== list bucket"

# output will have time and bucket name
#aws s3 ls

# output only bucket name
aws s3api list-buckets | jq -r '.Buckets | sort_by(.CreationDate) | reverse | .[] | .Name'

# output only 0~4 bucket name
#aws s3api list-buckets | jq -r '.Buckets | sort_by(.CreationDate) | reverse | .[0:5] | .[] | .Name'

