#!/usr/bin/env bash

echo "== deploy s3 bucket via CFN"

STACK_NAME="cfn-s3-simple"


aws cloudformation deploy \
  --template-file template.yaml \
  --region ca-central-1 \
  --stack-name $STACK_NAME 



 #--no-execute-changeset \
 #force the changeset to be created but not executed
 #but you can use the changeset to review the changes before executing them